### ISSUE TITLE
[Bug]: Puppeteer PDF generation via Page.pdf() method

### ISSUE THREAD

**Issue by GiovaniMFMurari** [cloudflare/puppeteer#37]
### Bug description

I was creating a simple html to pdf converter when I stumbled into a little issue with all the current version of the fork. 

In the current implementation of the Page.pdf method in the @cloudflare/puppeteer fork, the Readable stream returned by Page.createPDFStream is converted to a Buffer by the function getReadableAsBuffer in puppeteer `src/common
/util.ts`, where the problem is at. The getReadableAsBuffer function tries to iterate over a non iterable object(node:stream/Readable), what causes an `TypeError: readable is not async iterable` exception. 

It can be easily solved by using Page.createPDFStream directly, but is still an issue which is not present in the @puppeteer/puppeteer-core package.

Steps to reproduce the problem:

1. Launch puppeteer and instantiate a Page with some content:
```
const browser = await puppeteer.launch(env.MYBROWSER);
const page = await browser.newPage();
await page.setContent('<h1>HELLO CLOUDFLARE</h1>', {
waitUntil: 'networkidle0',
});
```
2. Get the PDF:
```
 await page.pdf({ displayHeaderFooter: true })
```

Below is the link of a repo to reproduce the issue.
https://github.com/GiovaniMFMurari/cf-puppeteer-pdf-gen-test

### Puppeteer version

0.0.6

### Node.js version

16, 18 and 20

### npm version

using pnpm 8.15.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
✘ [ERROR] Uncaught (in response) TypeError: readable is not async iterable

      at getReadableAsBuffer
      at Page.pdf
      at async Object.fetch
      at async drainBody
```

**Comment by emilthemaker** [comment]
Getting this too! Any update?

**Comment by emilthemaker** [comment]
UPDATE: here's a working workaround.

`
export default async function markdownToR2Pdf(env: Env) {
	console.log("Starting markdownToR2Pdf function");
	let html = `
    <html>
        <body>
            <h1>Hello World</h1>
        </body>
    </html>
    `;

	console.log("Launching browser");
	const browser = await puppeteer.launch(env.BROWSER);
	console.log("Browser launched");

	console.log("Creating new page");
	const page = await browser.newPage();
	console.log("New page created");

	console.log("Setting page content");
	await page.setContent(html);
	console.log("Page content set");

	console.log("Waiting for network idle");
	await page.waitForNetworkIdle();
	console.log("Network is idle");

	console.log("Generating PDF");
	const pdfStream = await page.createPDFStream({
		format: "A4",
		printBackground: true,
	});
	console.log("PDF stream created successfully");

	// Collect PDF data into a buffer
	const chunks: Uint8Array[] = [];
	return new Promise<string>((resolve, reject) => {
		pdfStream.on("data", (chunk: Uint8Array) => chunks.push(chunk));
		pdfStream.on("end", async () => {
			const pdfBuffer = Buffer.concat(chunks);
			console.log("PDF buffer created");

			// Upload PDF to R2 bucket
			const objectName = `pdf_${Date.now()}.pdf`;
			await env.SALES_FILES_BUCKET.put(objectName, pdfBuffer);
			console.log("PDF uploaded to R2 bucket");

			// Generate a public URL for the PDF
			const pdfUrl = await env.SALES_FILES_BUCKET.createSignedUrl({
				bucket: env.SALES_FILES_BUCKET,
				key: objectName,
				expiresIn: 3600, // URL expires in 1 hour
			});

			await page.close();
			await browser.close();

			resolve(pdfUrl);
		});
		pdfStream.on("error", (error) => {
			reject(error);
		});
	});
}

`

**Comment by danielgek** [comment]
@GiovaniMFMurari and @emilthemaker we released an update recently and we can't reproduce this anymore, can you give it another try ?

**Comment by danielgek** [comment]
We are closing this, feel free to reopen if you still get this error with the recent versions

**Comment by dpeek** [comment]
This bug still exists in 0.0.13, throwing the same error:

This works:

```typescript
function streamToBuffer(stream: NodeJS.ReadableStream) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: any[] = [];
    stream.on('data', (chunk) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', (err) => reject(err));
  });
}

const stream = await page.createPDFStream();
const buffer = await streamToBuffer(stream);
```

This fails with `TypeError: readable is not async iterable`

```typescript
const buffer = await page.pdf();
```

**Comment by danielgek** [comment]
@dpeek can you get me a full example ? i just tested and i can't reproduce
